# Generated by Django 2.1.7 on 2019-06-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_auto_20190601_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mid',
        ),
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
